import ast
from pathlib import Path
from typing import List, Dict

class CodeAnalyzer:
    def __init__(self, source_path: Path):
        self.source_path = source_path
        self.tree = self._parse_file()

    def _parse_file(self) -> ast.AST:
        """Reads and parses the source file."""
        with open(self.source_path, "r", encoding="utf-8") as f:
            return ast.parse(f.read())

    def extract_functions(self) -> List[Dict]:
        """Extracts global functions and class methods."""
        functions = []
        
        for node in ast.walk(self.tree):
            # Extract global functions
            if isinstance(node, ast.FunctionDef):
                # Ignore private/magic methods by default
                if node.name.startswith("__"):
                    continue
                
                # Filter out 'self' for class methods
                args = [arg.arg for arg in node.args.args if arg.arg != 'self']
                
                functions.append({
                    "name": node.name,
                    "args": args,
                    "docstring": ast.get_docstring(node)
                })
                
        return functions

def generate_test_content(source_file: Path, functions: List[Dict]) -> str:
    """Generates the text content for the test file."""
    module_name = source_file.stem
    
    # Test file header
    # Uses explicit import to avoid namespace pollution and conflicts
    content = [
        "import pytest",
        f"import {module_name} # Fix route to the import if needed", 
        "",
        "# Tests generated by pytest-forger",
        ""
    ]

    if not functions:
        content.append(f"# No public functions found in {source_file.name}")
        content.append("def test_placeholder():")
        content.append("    assert True")

    for func in functions:
        func_name = func['name']
        test_name = f"test_{func_name}"
        
        # Prepare arguments initialization
        args_list = func['args']
        args_init = [f"{arg} = None" for arg in args_list]
        args_call = ", ".join(args_list)

        content.append(f"def {test_name}():")
        
        # Add docstring if available
        if func['docstring']:
            summary = func['docstring'].splitlines()[0]
            content.append(f'    """Test for {func_name}: {summary}"""')
        
        content.append("    # Arrange")
        if args_init:
            content.append(f"    {'; '.join(args_init)}  # TODO: Assign real values")
        else:
            content.append("    # (No arguments required)")
        
        content.append("    # Act")
        # Explicit call: module.function()
        content.append(f"    # result = {module_name}.{func_name}({args_call})")
        
        content.append("    # Assert")
        content.append("    assert True  # TODO: Replace with: assert result == expected_value")
        content.append("")

    return "\n".join(content)